apiVersion: v1
kind: Service
metadata:
  annotations:
  name: echorest-service
  namespace: echorest-namespace
  labels:
    app: echorest-app
spec:
  selector:
    app: echorest-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echorest-deployment
  namespace: echorest-namespace
  labels:
    app: echorest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echorest-app
  template:
    metadata:
      labels:
        app: echorest-app
    spec:
      containers:
        - name: echorest
          image: ap-mumbai-1.ocir.io/idx9wbxtnehn/echorest:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
